blueprints/blog.py
from flask import Blueprint, render_template, redirect, request, flash, jsonify
from models import db, Article, Category, ContactMessage
from sqlalchemy import desc


blog = Blueprint('blog', __name__)


@blog.route('/')
@blog.route('/articles')
def index():
    articles = Article.query.filter(Article.status == 1) \
                    .order_by(desc(Article.created_at)) \
                    .all()
    return render_template('pages/index.html', articles=articles)


@blog.route('/articles/<slug>')
def read_article(slug):
    article = Article.query.join(Category, Article.category == Category.id) \
                .add_columns(Article.title, Article.updated_at, Article.created_at, Article.content, Category.name.label('category')) \
                .filter(Article.slug == slug).first_or_404()
    return render_template('pages/read-article.html', article=article)

@blog.route('/about')
def about_me():
    return render_template('pages/about.html')


@blog.route('/subscribe', methods=['GET', 'POST'])
def subscribe():
    response = 'Thank you for subscribing. I was too lazy to edit this piece....'
    return jsonify(response)



@blog.route('/contact', methods=['GET', 'POST'])
def contact_me():
    if request.method == 'POST':
        person_name = request.form.get('name')
        person_email = request.form.get('email')
        message = request.form.get('message')
        if person_email and person_name and message:
            try:
                contact_message = ContactMessage(name=person_name, email=person_email, message=message)
                db.session.add(contact_message)
                db.session.commit()
                flash("Your message has been sent. I will respond to you soon.", "success")
            except Exception as error:
                print('Error: {}'.format(str(error)))
                flash("Uh oh! Something crashed, but don't worry. It'll be fixed soon... Probably...", "danger")
        else:
            flash("Well, could you try entering all the fields?", "danger")
    return render_template('pages/contact.html')

templates/pages/about.html
{% extends "layouts/base.html" %}

{% block title %} About me {% endblock %}

{% block subtitle %}
<div class="sub-title">
    <h1>About Me</h1>
    <a href="{{ url_for('blog.contact_me')}}"><i class="icon-envelope"></i></a>
</div>
{% endblock %}
{% block content %}
<div class="col-md-12 content-page">
    <div class="col-md-12 blog-post">


        <!-- My Intro Start -->
        <div class="post-title margin-bottom-30">
            <h2>Hi, I am <span class="main-color">Kudzai Tsapo</span></h2>
    
            <ul class="knowledge">
                <li class="bg-color-1">Web Developer</li>
                <li class="bg-color-4">Author</li>
                <li class="bg-color-6">Aspiring Data Scientist</li>
                <li class="bg-color-5">Consultant</li>
                <li class="bg-color-4">Idealist</li>
            </ul>
        
        </div>
        <!-- My Intro End -->
    
    
        <p>
            I am an experienced Software Engineer with a demonstrated history of working in the information technology and services industry. 
            My skills include Python, Java (<em>even though I prefer C#</em>), SQL (Postgres, MySQL, MSSQL) and NoSQL (MongoDB). I have a bit of knowledge in a lot of frameworks
            some of which include Spring Boot (Java), Express (NodeJS), Flask & Django (Python) and Laravel (PHP).I have a Bachelor's degree in Computer Science
            from University of Zimbabwe ( class of 2019 ). 
        </p>
        <p>
            I like writing articles, and with my friends, we usually do writing sessions in which we get a topic, and everyone writes something on the topic. It's quite fun,
            well, for me that is, even though I admit that it can be quite torturous. Well, I also like coding scripts like web crawlers and stuff. And of course, I like reading
            a lot of things, from business books, self help books, fictions, psychological and so on.
        </p>
        <p>
            I also love learning about blockchain and AI, and no, I don't think AI will take over the world. Well, not any time soon. If you have anything you need to ask,
            or talk about in general, or even yell at me for (<em> umm, be careful about this one...</em>), feel free to get in touch. I'll try my best to be available....
        </p>
    
    
    
    
        <!-- My Service Start -->
        <div class="post-title">
            <h2>My <span class="main-color">Services</span></h2> 
        </div>
        
        <div class="list list-style-2 margin-top-30">
            <ul>
                <li>Software Development</li>
                <li>Data analytics</li>
                <li>Software consulting</li>
                <li>Article writing</li>
            </ul>
        </div>
        <!-- My Service End --> 
    
    </div>  

    <div class="col-md-12 text-center">
        <a href="{{ url_for('blog.contact_me')}}" data-toggle="tooltip" data-placement="top" title="Visit on my contact page to get in touch." class="load-more-button">Contact</a>
    </div>
    
</div>
{% endblock %}

templates/pages/contact.html
{% extends "layouts/base.html" %}

{% block title %} Get in touch {% endblock %}

{% block subtitle %}
<div class="sub-title">
    <h1>Contact Me</h1>
    <a href="{{ url_for('blog.index')}}"><i class="icon-home"></i></a>
</div>
{% endblock %}
{% block content %}
<div class="col-md-12 content-page">
    <div class="col-md-12 blog-post">
                
        <!-- Contact Me Start -->
        <div class="post-title margin-top-70">
            <h2>Get in <span class="main-color">touch</span></h2>
        </div>
            
            
        <div class="row">
            <div class="col-md-4 col-sm-4">
                <div class="contact-us-detail">  
                    <i class="icon-screen-smartphone color-6"></i>
                    <p><a href="tel:+263783449906">+263 78 344 9906</a></p>
                </div>
            </div>

            <div class="col-md-4 col-sm-4">
                <div class="contact-us-detail">
                    <i class="icon-envelope-open color-5"></i>
                    <p><a href="mailto:kudzaitsapo@gmail.com">kudzaitsapo@gmail.com</a></p>
                </div>
            </div>

            <div class="col-md-4 col-sm-4">
                <div class="contact-us-detail">
                    <i class="icon-clock color-3"></i>
                    <p>Mon - Fri 09:00 – 15:00</p>
                </div>
            </div>
        </div>

         
        <div class="row margin-top-30">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12">
                        {% with messages = get_flashed_messages(with_categories=true) %}
                            {% if messages %}
                                <ul class=flashes>
                                {% for category, message in messages %}
                                    <li class="alert alert-{{ category }}">{{ message }}</li>
                                {% endfor %}
                                </ul>
                            {% endif %}
                        {% endwith %}
                    </div>
                </div>
                <div class="row">
                    <form method="POST" action="">

                        <div class="col-sm-6">
                            <div class="form-group">
                                <input type="text" name="name" id="name" class="form-control" required placeholder="Your Name">
                            </div>
                        </div>
        
                        <div class="col-sm-6">
                            <div class="form-group">
                                <input type="email" id="email" name="email" class="form-control" required placeholder="Your Email Address">
                            </div>
                        </div>
    
        
                        <div class="col-sm-12">
                            <div class="textarea-message form-group">
                                <textarea id="message" name="message" class="textarea-message form-control" required placeholder="Your Message" rows="5"></textarea>
                            </div>
                        </div>


                        <div class="text-center">      
                            <button type="submit" class="load-more-button">Send</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
        <!-- Contact Me End -->
    </div>
</div>

{% endblock %}

templates/pages/index.html
{% extends "layouts/base.html" %}

{% block title %} My notes {% endblock %}

{% block meta %}
<meta name="description" content="150 words">
<meta name="author" content="Kudzai Tsapo">
<meta name="url" content="http://www.yourdomainname.com">
<meta name="copyright" content="knotes">
<meta name="robots" content="index,follow">
{% endblock %}

{% block subtitle %}
<div class="sub-title">
    <h1>Kudzi Notes</h1>
 <a href="{{ url_for('blog.contact_me')}}"><i class="icon-envelope"></i></a>
</div>

{% endblock %}

{% block content %}

{% for article in articles %}
<div class="col-md-12 content-page">
    <!-- Blog Post Start -->
    <div class="col-md-12 blog-post">
        <div class="post-title">
          <a href="{{ url_for('blog.read_article', slug=article.slug)}}"><h2>{{ article.title }}</h2></a>
        </div>  
        <div class="post-info">
            <span>{{ article.created_at.strftime('%B %d, %Y')}} </span>
        </div>
    </div>
    <!-- Blog Post End -->
</div>
{% else %}
<div class="col-md-12 content-page">
    <!-- Blog Post Start -->
    <div class="col-md-12 blog-post">
        <div class="post-info">
            <span>August 2020</span>
        </div>  
        <p>No articles have been added yet...</p>
    </div>
    <!-- Blog Post End -->
</div>
{% endfor %}

{% endblock %}

templates/pages/read-article.html
{% extends "layouts/base.html" %}

{% block title %} {{ article.title }} {% endblock %}
{% block subtitle %}
<div class="sub-title">
    <a href="{{ url_for('blog.index')}}" title="Go to Home Page"><h1>Back Home</h1></a>
    <a href="{{ url_for('blog.contact_me')}}" class="smoth-scroll"><i class="icon-bubbles"></i></a>
</div>

{% endblock %}

{% block content %}
<div class="col-md-12 content-page">
    <div class="col-md-12 blog-post">
                            	
                                
        <!-- Post Headline Start -->
        <div class="post-title">
            <h2>{{ article.title }}</h2> 
        </div>
        <!-- Post Headline End -->
        
            
        <!-- Post Detail Start -->
        <div class="post-info">
            <span>Published: {{ article.created_at.strftime('%B %d, %Y')}}</a></span><br>
            <span>Last Edited: 
                {% if article.updated_at %}
                    {{ article.updated_at.strftime('%B %d, %Y')}}
                {% else %}
                    Not edited
                {% endif %}
            </span>
        </div>
        <!-- Post Detail End -->
            
            
       {{ article.content | safe}}
            
            
            
        <!-- You May Also Like Start -->
        <!-- <div class="you-may-also-like margin-top-50 margin-bottom-50">
            <h3>You may also like</h3>
                <div class="row">
            
                <div class="col-md-4 col-sm-6 col-xs-12">
                <a href="#"><p>Make mailchimp singup form working with ajax using jquery plugin</p></a>
                </div>

                <div class="col-md-4 col-sm-6 col-xs-12">
                <a href="#"><p>How to design elegant e-mail newsletter in html for wish christmas to your subscribers?</p></a>
                </div>

                <div class="col-md-4 col-sm-6 col-xs-12">
                <a href="#"><p>How to customize a wordpress theme entirely from scratch using a child theme?</p></a>
                </div>
            
            </div>
        </div> -->
        <!-- You May Also Like End -->
            
            
            
            
        <!-- Post Comment Start -->
        <div id="comment" class="comment">
        <h3>Discuss about post</h3>
            
            
            <!-- You can use here any third party commenting plugin here like disqus.com-->

        </div>
        <!-- Post Comment End -->

    </div>    
</div>
                              
                         
{% endblock %}