blueprints/admin.py
from flask import Blueprint, render_template, flash, redirect, url_for, request, jsonify, current_app
from flask_login import login_required, current_user, login_user, logout_user
from forms import LoginForm
from models import db, User, Article, Category, ContactMessage
from werkzeug.urls import url_parse
from werkzeug.utils import secure_filename
from slugify import slugify

import os


admin_bp = Blueprint('admin', __name__)

@admin_bp.route('/')
@login_required
def index():
    return render_template('admin/index.html')


@admin_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('admin.index'))


    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter(User.email == form.email.data).first()
        if user and user.check_password(form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            if not next_page or url_parse(next_page).netloc != '':
                next_page = url_for('admin.index')

            return redirect(next_page)
        else:
            flash('Invalid username or password')
    return render_template('admin/login.html', form=form)


@admin_bp.route('/articles')
@login_required
def articles():
    page = request.args.get('page', 1, type=int)
    articles = Article.query.join(Category, Article.category == Category.id) \
                    .add_columns(Article.id, Article.title, Article.updated_at, Article.created_at, Article.status, Category.name.label('category')) \
                    .paginate(page, 10, False)
    next_url = url_for('admin.articles', page=articles.next_num) if articles.has_next else None
    prev_url = url_for('admin.articles', page=articles.prev_num) if articles.has_prev else None
    return render_template('admin/articles.html', articles=articles.items, next_url=next_url, prev_url=prev_url)


@admin_bp.route('/articles/add-article', methods=['GET', 'POST'])
@login_required
def add_article():
    categories = Category.query.all()
    if request.method == 'POST':
        response = { 'icon': 'error', 'message': '' }
        try:
            title = request.form.get('title')
            category = request.form.get('category')
            article_content = str(request.form.get('article')).replace('font-size: 1rem;', '')
            status = request.form.get('status')

            article = Article(title=title, slug=slugify(title), category=category, content=article_content, status=status)
            db.session.add(article)
            db.session.commit()
            response['icon'] = 'success'
            response['message'] = 'Successfully added article.'
        except Exception as error:
            print('[-] Error {}'.format(str(error)))
            response['message'] = 'Oops! Failed to add this one!'
        return jsonify(response)
    return render_template('admin/add-article.html', categories=categories)


@admin_bp.route('/categories')
@login_required
def categories():
    categories = Category.query.all()
    return render_template('admin/categories.html', categories=categories)

@admin_bp.route('/categories/add-category', methods=['GET', 'POST'])
@login_required
def add_category():
    if request.method == 'POST':
        category_name = request.form.get('category')
        response = { 'icon': 'error', 'message': '' }
        try:
            category = Category(name=category_name)
            db.session.add(category)
            db.session.commit()
            response['icon'] = 'success'
            response['message'] = 'Successfully added category!'
        except Exception as error:
            print('[-] Error: {}'.format(str(error)))
            response['message'] = 'Oops! That one failed!'

        return jsonify(response)
    return render_template('admin/add-category.html')


@admin_bp.route('/categories/<id>/edit', methods=['GET', 'POST'])
@login_required
def edit_category(id):
    category = Category.query.get(int(id))
    if request.method == 'POST':
        category_name = request.form.get('category')
        response = { 'icon': 'error', 'message': '' }
        try:
            category.name = category_name
            db.session.commit()
            response['icon'] = 'success'
            response['message'] = 'Yipppeee, we saved it.'
        except Exception as error:
            print('[-] Error: {}'.format(str(error)))
            response['message'] = 'Uh oh! Something crashed!'
        return jsonify(response)
    return render_template('admin/edit-category.html', category=category)


@admin_bp.route('/articles/<id>/edit', methods=['GET', 'POST'])
@login_required
def edit_article(id):
    article = Article.query.filter(Article.id == id).first()
    categories = Category.query.all()

    if request.method == 'POST':
        response = { 'icon': 'error', 'message': '' }
       
        try:
            article.title = request.form.get('title')
            article.content = str(request.form.get('article')).replace('font-size: 1rem;', '')
            article.status = request.form.get('status')
            article.category = request.form.get('category')
            db.session.commit()
            response['icon'] = 'success'
            response['message'] = 'Successfully saved the article'
        except Exception as error:
            print('[-] Error: {}'.format(str(error)))
            response['message'] = 'Oops! That one failed!'
        return jsonify(response)
    return render_template('admin/edit-article.html', article=article, categories=categories)


@admin_bp.route('/messages')
@login_required
def get_messages():
    page = request.args.get('page', 1, type=int)
    messages = ContactMessage.query.paginate(page, 20, False)
    next_url = url_for('admin.get_messages', page=messages.next_num) if messages.has_next else None
    prev_url = url_for('admin.get_messages', page=messages.prev_num) if messages.has_prev else None
    return render_template('admin/messages.html', messages = messages.items, next_url=next_url, prev_url=prev_url)


@admin_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('admin.login'))

blueprints/blog.py
from flask import Blueprint, render_template, redirect, request, flash, jsonify
from models import db, Article, Category, ContactMessage
from sqlalchemy import desc


blog = Blueprint('blog', __name__)


@blog.route('/')
@blog.route('/articles')
def index():
    articles = Article.query.filter(Article.status == 1) \
                    .order_by(desc(Article.created_at)) \
                    .all()
    return render_template('pages/index.html', articles=articles)


@blog.route('/articles/<slug>')
def read_article(slug):
    article = Article.query.join(Category, Article.category == Category.id) \
                .add_columns(Article.title, Article.updated_at, Article.created_at, Article.content, Category.name.label('category')) \
                .filter(Article.slug == slug).first_or_404()
    return render_template('pages/read-article.html', article=article)

@blog.route('/about')
def about_me():
    return render_template('pages/about.html')


@blog.route('/subscribe', methods=['GET', 'POST'])
def subscribe():
    response = 'Thank you for subscribing. I was too lazy to edit this piece....'
    return jsonify(response)



@blog.route('/contact', methods=['GET', 'POST'])
def contact_me():
    if request.method == 'POST':
        person_name = request.form.get('name')
        person_email = request.form.get('email')
        message = request.form.get('message')
        if person_email and person_name and message:
            try:
                contact_message = ContactMessage(name=person_name, email=person_email, message=message)
                db.session.add(contact_message)
                db.session.commit()
                flash("Your message has been sent. I will respond to you soon.", "success")
            except Exception as error:
                print('Error: {}'.format(str(error)))
                flash("Uh oh! Something crashed, but don't worry. It'll be fixed soon... Probably...", "danger")
        else:
            flash("Well, could you try entering all the fields?", "danger")
    return render_template('pages/contact.html')

templates/layouts/_navbar.html
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{ url_for('static', filename='admin/img/user1-128x128.jpg')}}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{ url_for('static', filename='admin/img/user8-128x128.jpg')}}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{ url_for('static', filename='admin/img/user3-128x128.jpg')}}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button"><i
            class="fas fa-th-large"></i></a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

templates/layouts/_sidebar.html
 <!-- Main Sidebar Container -->
 <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{url_for('admin.index')}}" class="brand-link">
      <img src="{{ url_for('static', filename='admin/img/logo.png')}}" alt="My Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">My Blog</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{ url_for('static', filename='admin/img/avatar.png')}}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ current_user.username }}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
            <li class="nav-item has-treeview">
              <a href="{{ url_for('admin.articles')}}" class="nav-link">
                <i class="nav-icon fa fa-book-reader"></i>
                <p>
                  Articles
                </p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{ url_for('admin.categories')}}" class="nav-link">
                <i class="nav-icon fa fa-user-tie"></i>
                <p>
                  Categories
                </p>
              </a>
            </li>

            <li class="nav-item">
              <a href="{{ url_for('admin.get_messages')}}" class="nav-link">
                <i class="nav-icon fa fa-comment-alt"></i>
                <p>
                  Messages
                </p>
              </a>
            </li>

            <li class="nav-item">
              <a href="{{ url_for('admin.logout')}}" class="nav-link">
                <i class="nav-icon fa fa-sign-out-alt"></i>
                <p>
                  Logout
                </p>
              </a>
            </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

templates/layouts/admin.base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>
      {% block title %}{% endblock %}
  </title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{{ url_for('static', filename='admin/vendors/fontawesome-free/css/all.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ url_for('static', filename='admin/css/adminlte.min.css')}}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  {% block stylesheets %}{% endblock %}
  
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

    {% include 'layouts/_navbar.html' %}

    {% include 'layouts/_sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Starter Page</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ url_for('admin.index')}}">Home</a></li>
              <li class="breadcrumb-item active">Starter Page</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    {% block content %}{% endblock %} 
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        My Blog
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2020 <a href="#">Kudzai Tsapo</a>.</strong> All rights reserved.
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{{ url_for('static', filename='admin/vendors/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap 4 -->
<script src="{{ url_for('static', filename='admin/vendors/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{ url_for('static', filename='admin/js/adminlte.min.js')}}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    
    <!-- Meta Tag -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <!-- SEO -->
    {% block meta %}{% endblock %}
    
    
    <title>KNotes - {% block title %}{% endblock %}</title>
    
    <!-- All CSS Plugins -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/plugin.css')}}">
    
    <!-- Main CSS Stylesheet -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css')}}">
    
    <!-- Google Web Fonts  -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:400,300,500,600,700">
    
    
    <!-- HTML5 shiv and Respond.js support IE8 or Older for HTML5 elements and media queries -->
    <!--[if lt IE 9]>
	   <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
	   <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    

  </head>

 <body>

	
     
	 <!-- Preloader Start -->
    <div class="preloader">
	    <div class="rounder"></div>
    </div>
    <!-- Preloader End -->

    <div id="main">
      <div class="container">
          <div class="row">
            
                <!-- About Me (Left Sidebar) Start -->
                <div class="col-md-3">
                  <div class="about-fixed">
                  
                    <div class="my-pic">
                      <img src="{{ url_for('static', filename='images/pic/my-logo.png')}}" alt="">
                      <a href="javascript:void(0)" class="collapsed" data-target="#menu" data-toggle="collapse"><i class="icon-menu menu"></i></a>
                        <div id="menu" class="collapse">
                          <ul class="menu-link">
                              <li><a href="{{ url_for('blog.about_me')}}">About</a></li>
                              <li><a href="{{ url_for('blog.contact_me')}}">Contact</a></li>
                          </ul>
                        </div>
                      </div>
                    
                    
                    
                    <div class="my-detail">
                    
                      <!-- <div class="white-spacing">
                          <span>
                            <em>Aurum Potestas Est</em>
                          </span>
                          <span class="my-sub-title">Software Developer</span>
                      </div>  -->
                      
                      <ul class="social-icon">
                        <li><a href="https://www.facebook.com/kudzai.tsapo" target="_blank" class="facebook"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="https://twitter.com/kudzaitsapo" target="_blank" class="twitter"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="https://www.linkedin.com/in/kudzai-tsapo-227192150/" target="_blank" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="https://github.com/kudzaitsapo" target="_blank" class="github"><i class="fa fa-github"></i></a></li>
                      </ul>

                  </div>
                </div>
              </div>
              <!-- About Me (Left Sidebar) End -->
              
              <!-- Blog Post (Right Sidebar) Start -->
              <div class="col-md-9">
                  <div class="col-md-12 page-body">
                      <div class="row">
                          
                          {% block subtitle %}{% endblock %}
                      
                          {% block content %}{% endblock %}
                          
                              
                      </div>
                      
                  
                  
                      <!-- Subscribe Form Start -->
                      <div class="col-md-8 col-md-offset-2">
                          <form id="mc-form" method="post" action="{{ url_for('blog.subscribe')}}">
                          
                              <div class="subscribe-form margin-top-20">
                                      <input id="mc-email" type="email" placeholder="Email Address" class="text-input">
                                  <button class="submit-btn" type="submit">Submit</button>
                              </div>
                              <p>Subscribe to my weekly newsletter</p>
                              <label for="mc-email" class="mc-label"></label>
                          </form>
                          
                      </div>
                      <!-- Subscribe Form End -->
                      
                  </div>
                  
                  
                  <!-- Footer Start -->
                  <div class="col-md-12 page-body margin-top-50 footer">
                      <footer>
                          <ul class="menu-link">
                              <li><a href="{{ url_for('blog.index')}}">Home</a></li>
                              <li><a href="{{ url_for('blog.about_me')}}">About</a></li>
                              <li><a href="{{ url_for('blog.contact_me')}}">Contact</a></li>
                          </ul>
                          
                          <p>© Copyright 2020 KNotes. All rights reserved</p>
                          
                          
                          <!-- UiPasta Credit Start -->
                          <div class="uipasta-credit">Design By <a href="https://www.uipasta.com" target="_blank">UiPasta</a></div>
                          <!-- UiPasta Credit End -->

                      
                      </footer>
                  </div>
                  <!-- Footer End -->
                  
                  
              </div>
              <!-- Blog Post (Right Sidebar) End -->
              
          
          
              </div>
        </div>
    </div>
    
    
    
    <!-- Back to Top Start -->
    <a href="#" class="scroll-to-top"><i class="fa fa-long-arrow-up"></i></a>
    <!-- Back to Top End -->
    
    
    <!-- All Javascript Plugins  -->
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.min.js')}}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/plugin.js')}}"></script>
    
    <!-- Main Javascript File  -->
    <script type="text/javascript" src="{{ url_for('static', filename='js/scripts.js')}}"></script>

    
   </body>
 </html>